```{r}
if (!require(MCMCpack)) {
  install.packages("MCMCpack")
  library(MCMCpack)
}
```

```{r}
#' This function creates a 2x2 contingency table from 
#' the specified exposure and outcome columns in the provided dataset.
#'
#' @param data Dataset.
#' @param exposure_col String, name of the exposure column in the dataset.
#' @param outcome_col String , name of the outcome column in the dataset.
#'
#' @return List containing:
#'   p_0e0d: The count of rows where both exposure and outcome are 0.
#'   p_0e1d: The count of rows where exposure is 0 and outcome is 1.
#'   p_1e0d: The count of rows where exposure is 1 and outcome is 0.
#'   p_1e1d: The count of rows where both exposure and outcome are 1.
#'   n: The total number of observations.
#'   contingency_table: The 2x2 contingency table with row and column totals.
#' }
#'
#' @examples
#' # Example usage:
#' data <- data.frame(exposure = c(0, 0, 1, 1, 0, 1, 0, 1),
#'                    outcome = c(0, 1, 0, 1, 0, 1, 1, 0))
#' result <- create_2x2_contingency_table(data, "exposure", "outcome")
#'
#' @export
create_2x2_contingency_table <- function(data, exposure_col, outcome_col) {
  # Create a 2x2 table of chosen columns with dimension names
  table <- table(data[[exposure_col]], data[[outcome_col]], dnn = c(exposure_col, outcome_col))

  # Count the number of each possible combination of exposure and outcome
  x_0e0d <- sum(data[[exposure_col]] == 0 & data[[outcome_col]] == 0)
  x_0e1d <- sum(data[[exposure_col]] == 0 & data[[outcome_col]] == 1)
  x_1e0d <- sum(data[[exposure_col]] == 1 & data[[outcome_col]] == 0)
  x_1e1d <- sum(data[[exposure_col]] == 1 & data[[outcome_col]] == 1)
  n    <- sum(table)

  # Add row and column totals to the contingency table
  contingencyTableWithTotals <- addmargins(table)

  return(list(x_0e0d = x_0e0d, x_0e1d = x_0e1d, x_1e0d = x_1e0d, x_1e1d = x_1e1d, n = n, contingency_table = contingencyTableWithTotals))
}
```

```{r}
#' This function calculates the population attributable risk (PAR) for a binary exposure and outcome.
#' PAR = P(D+) - P(D+| E-) = (a + c)/(a + b + c + d) - (c + d)/c
#'
#' @param a The count of rows where both exposure and outcome are 0.
#' @param b The count of rows where exposure is 0 and outcome is 1.
#' @param c The count of rows where exposure is 1 and outcome is 0.
#' @param d The count of rows where both exposure and outcome are 1.
#' @param n The total number of observations.
#' 
#' @return The population attributable risk (PAR).
#' 
#' @examples
#' # Example usage:
#' PAR <- calculate_PAR(1, 2, 3, 4, 10)
#' 
#' @export
calculate_PAR <- function(x) {
  a <- x[1]
  b <- x[2]
  c <- x[3]
  d <- x[4]
  n <- x[5]
  PAR <- (a + c)/(a + b + c + d) - (c + d)/c
  return(PAR)
}
```

```{r}
#' This function print the Population Attributable Risk (PAR) and its specified confidence interval
#' based on a 2x2 contingency table created from the provided data.
#'
#' @param data dataset.
#' @param exposure_col String, name of the column representing the exposure variable.
#' @param outcome_col String, name of the column representing the outcome variable.
#' @param interval Interval for the confidence interval (default is 0.95). Possible values are
#' between 0 and 1.
#'
#' @return None
#'
#' @examples
#' \dontrun{
#' data <- data.frame(exposure = sample(c(0, 1), 100, replace = TRUE),
#'                    outcome = sample(c(0, 1), 100, replace = TRUE))
#' calculate_PAR_and_CI(data, "exposure", "outcome", 0.5)
#' }
calculate_PAR_and_CI <- function(data, exposure_col, outcome_col, interval = 0.95, prior = 1) {
  # Create a 2x2 contingency table
  ct <- create_2x2_contingency_table(data, exposure_col, outcome_col)
  cat("Contingency table: ", "\n")
  print(ct$contingency_table)

  # Calculate the population attributable risk
  par <- calculate_PAR(c(ct$x_0e0d, ct$x_0e1d, ct$x_1e0d, ct$x_1e1d, ct$n))
  cat("PAR is: ", par, "\n")

  # Sample from the Dirichlet distribution 10,000 times
  # + prior is to add the prior distribution's effect
  samples <- rdirichlet(10000, c(ct$x_0e0d + prior, ct$x_0e1d + prior, ct$x_1e0d + prior, ct$x_1e1d + prior, ct$n))
  samples <- apply(samples, 2, function(x) x * ct$n)

  par_samples <- apply(samples, 1, calculate_PAR)

  # Calculate the confidence interval
  confidence_interval <- quantile(par_samples, c((1-interval)/2, 1-(1-interval)/2))

  # Display the first few samples
  cat(interval*100, "% confidence interval is: ", confidence_interval, "\n")

  # Display a histogram of the samples
  hist(par_samples, main = "Histogram of PAR samples", xlab = "PAR", ylab = "Frequency")
  plot(par_samples)
}
```

```{r}
# Specify the file path.
file_path <- "../data.csv"

# Use read.csv() function to read the file
data <- read.csv(file_path)

# Print contingency table, PAR, and confidence interval
calculate_PAR_and_CI(data, "active", "cardio", 0.95, 1)
```
